from __future__ import annotations

import asyncio
import socket
from collections.abc import Callable, Iterable, Sequence
from contextvars import Context
from typing import IO, TYPE_CHECKING, Any, Literal, final

from typing_extensions import disjoint_base

if TYPE_CHECKING:
    from ._connect import _HangupWatch

KIND_TCP: Literal[0]
KIND_PIPE: Literal[1]
KIND_PIPE_WRITE: Literal[2]
PROCESS_DETACHED: int
PROCESS_SETUID: int
PROCESS_SETGID: int

def libuv_version() -> str:
    """Return the version of the libuv build compiled into the extension."""

@final
class Handle:
    def cancel(self) -> None: ...
    def cancelled(self) -> bool: ...
    def get_context(self) -> Context: ...

@final
class TimerHandle(asyncio.TimerHandle):
    """Subtype of `asyncio.TimerHandle`, so the ordering the base defines over
    the deadline works.

    The base reads these while comparing and formatting handles; each is a
    read-only view of the native record rather than the base's own storage.
    """

    @property
    def _when(self) -> int | float: ...
    @property
    def _scheduled(self) -> bool: ...
    @property
    def _callback(self) -> Callable[..., object] | None: ...
    def cancel(self) -> None: ...
    def cancelled(self) -> bool: ...
    def when(self) -> int | float: ...

@final
class ThreadSafeHandle(asyncio.Handle):
    """Subtype of `asyncio.events._ThreadSafeHandle`; `cancel` and `cancelled`
    from a foreign thread wait out a callback that is mid-run."""

    def cancel(self) -> None: ...
    def cancelled(self) -> bool: ...

@final
class DatagramTransport(asyncio.Transport, asyncio.DatagramTransport):
    def get_extra_info(self, name: str, default: Any = None) -> Any: ...
    def is_closing(self) -> bool: ...
    def close(self) -> None: ...
    def abort(self) -> None: ...
    def get_protocol(self) -> asyncio.BaseProtocol: ...
    def set_protocol(self, protocol: asyncio.BaseProtocol, /) -> None: ...
    def sendto(self, data: Any, addr: Any = None) -> None: ...
    def get_write_buffer_size(self) -> int: ...
    def get_write_buffer_limits(self) -> tuple[int, int]: ...
    def set_write_buffer_limits(self, high: int | None = None, low: int | None = None) -> None: ...
    def pause_reading(self) -> None: ...
    def resume_reading(self) -> None: ...
    def _adopt_socket_view(self, view: socket.socket, /) -> None: ...
    def _start_receiving(self) -> None: ...

@final
class Process:
    def get_pid(self) -> int: ...
    def get_returncode(self) -> int | None: ...
    def send_signal(self, signum: int, /) -> None: ...

@final
class Transport(asyncio.Transport):
    @property
    def _protocol_paused(self) -> bool: ...
    def _adopt_pipe(self, pipe: IO[bytes] | _HangupWatch, /) -> None: ...
    def get_extra_info(self, name: str, default: Any = None) -> Any: ...
    def is_closing(self) -> bool: ...
    def close(self) -> None: ...
    def abort(self) -> None: ...
    def get_protocol(self) -> asyncio.BaseProtocol: ...
    def set_protocol(self, protocol: asyncio.BaseProtocol, /) -> None: ...
    def _adopt_socket_view(self, sock: socket.socket, /) -> None: ...
    def is_reading(self) -> bool: ...
    def pause_reading(self) -> None: ...
    def resume_reading(self) -> None: ...
    def write(self, data: bytes | bytearray | memoryview, /) -> None: ...
    def writelines(self, data: Iterable[bytes | bytearray | memoryview], /) -> None: ...
    def write_eof(self) -> None: ...
    def can_write_eof(self) -> bool: ...
    def get_write_buffer_size(self) -> int: ...
    def get_write_buffer_limits(self) -> tuple[int, int]: ...
    def _start_reading(self) -> None: ...
    def set_write_buffer_limits(self, high: int | None = None, low: int | None = None) -> None: ...
    def _force_close(self, exc: BaseException | None, /) -> None: ...

@disjoint_base
class Loop:
    """Native scheduling core: everything on a hot path lives here."""

    slow_callback_duration: float

    def call_soon(self, callback: Callable[..., object], *args: Any, context: Context | None = None) -> Handle: ...
    def call_soon_threadsafe(
        self, callback: Callable[..., object], *args: Any, context: Context | None = None
    ) -> ThreadSafeHandle: ...
    def call_later(
        self, delay: float, callback: Callable[..., object], *args: Any, context: Context | None = None
    ) -> TimerHandle: ...
    def call_at(
        self, when: float, callback: Callable[..., object], *args: Any, context: Context | None = None
    ) -> TimerHandle: ...
    def time(self) -> float: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def get_debug(self) -> bool: ...
    def set_debug(self, enabled: bool, /) -> None: ...
    def _set_slow_callback_monitoring(self, enabled: bool, /) -> None: ...
    def add_reader(self, fd: int, callback: Callable[..., object], *args: Any) -> None: ...
    def add_writer(self, fd: int, callback: Callable[..., object], *args: Any) -> None: ...
    def remove_reader(self, fd: int, /) -> bool: ...
    def remove_writer(self, fd: int, /) -> bool: ...
    def _run(self) -> None: ...
    def _defer_close(self, callback: Callable[[], object], /) -> None: ...
    def _close(self) -> None: ...
    def _timer_handle_cancelled(self, handle: TimerHandle, /) -> None: ...
    def _metrics(self) -> dict[str, int]: ...
    def _start_metrics(self, interval: float, callback: Callable[[dict[str, int]], object]) -> None: ...
    def _stop_metrics(self) -> None: ...
    def _getaddrinfo(
        self, host: str | bytes | None, port: str | bytes | int | None, family: int, type: int, proto: int, flags: int
    ) -> asyncio.Future[Sequence[tuple[int, int, int, str, tuple[Any, ...]]]]: ...
    def _getnameinfo(self, sockaddr: tuple[Any, ...], flags: int) -> asyncio.Future[tuple[str, str]]: ...
    def _make_transport(
        self,
        fd: int,
        kind: int,
        protocol: asyncio.BaseProtocol,
        waiter: asyncio.Future[None] | None,
        extra: dict[str, Any] | None,
        server: object | None,
    ) -> Transport: ...
    def _make_datagram_transport(
        self,
        fd: int,
        family: int,
        connected: bool,
        protocol: asyncio.BaseProtocol,
        extra: dict[str, Any],
    ) -> DatagramTransport: ...
    def _spawn_process(
        self,
        file: str,
        args: Sequence[str],
        env: Sequence[str] | None,
        cwd: str | None,
        stdio: Sequence[int],
        flags: int,
        uid: int,
        gid: int,
        on_exit: Callable[[int], object] | None,
    ) -> Process: ...
