from __future__ import annotations

import asyncio
from collections.abc import Callable, Iterable, Sequence
from contextvars import Context
from typing import Any, Literal

__all__ = ["Handle", "Loop", "TimerHandle", "Transport", "libuv_version"]

KIND_TCP: Literal[0]
KIND_PIPE: Literal[1]

def libuv_version() -> str:
    """Return the version of the libuv build compiled into the extension."""

class Handle(asyncio.Handle):
    def cancel(self) -> None: ...
    def cancelled(self) -> bool: ...

class TimerHandle(Handle, asyncio.TimerHandle):
    def when(self) -> float: ...

class Transport(asyncio.Transport):
    def get_extra_info(self, name: str, default: Any = None) -> Any: ...
    def is_closing(self) -> bool: ...
    def close(self) -> None: ...
    def abort(self) -> None: ...
    def get_protocol(self) -> asyncio.BaseProtocol: ...
    def set_protocol(self, protocol: asyncio.BaseProtocol) -> None: ...
    def is_reading(self) -> bool: ...
    def pause_reading(self) -> None: ...
    def resume_reading(self) -> None: ...
    def write(self, data: bytes | bytearray | memoryview) -> None: ...
    def writelines(self, data: Iterable[bytes | bytearray | memoryview]) -> None: ...
    def write_eof(self) -> None: ...
    def can_write_eof(self) -> bool: ...
    def get_write_buffer_size(self) -> int: ...
    def get_write_buffer_limits(self) -> tuple[int, int]: ...
    def _start_reading(self) -> None: ...
    def _set_write_buffer_limits(self, high: int | None, low: int | None) -> None: ...
    def _force_close(self, exc: BaseException | None) -> None: ...

class Loop:
    """Native scheduling core: everything on a hot path lives here."""

    slow_callback_duration: float

    def call_soon(self, callback: Callable[..., object], *args: Any, context: Context | None = None) -> Handle: ...
    def call_soon_threadsafe(
        self, callback: Callable[..., object], *args: Any, context: Context | None = None
    ) -> Handle: ...
    def call_later(
        self, delay: float, callback: Callable[..., object], *args: Any, context: Context | None = None
    ) -> TimerHandle: ...
    def call_at(
        self, when: float, callback: Callable[..., object], *args: Any, context: Context | None = None
    ) -> TimerHandle: ...
    def time(self) -> float: ...
    def stop(self) -> None: ...
    def is_running(self) -> bool: ...
    def is_closed(self) -> bool: ...
    def get_debug(self) -> bool: ...
    def set_debug(self, enabled: bool) -> None: ...
    def add_reader(self, fd: int, callback: Callable[..., object], *args: Any) -> None: ...
    def add_writer(self, fd: int, callback: Callable[..., object], *args: Any) -> None: ...
    def remove_reader(self, fd: int) -> bool: ...
    def remove_writer(self, fd: int) -> bool: ...
    def _run(self) -> None: ...
    def _close(self) -> None: ...
    def _timer_handle_cancelled(self, handle: TimerHandle) -> None: ...
    def _metrics(self) -> dict[str, int]: ...
    def _start_metrics(self, interval: float, callback: Callable[[dict[str, int]], object]) -> None: ...
    def _stop_metrics(self) -> None: ...
    def _getaddrinfo(
        self, host: str | bytes | None, port: str | bytes | int | None, family: int, type: int, proto: int, flags: int
    ) -> asyncio.Future[Sequence[tuple[int, int, int, str, tuple[Any, ...]]]]: ...
    def _getnameinfo(self, sockaddr: tuple[Any, ...], flags: int) -> asyncio.Future[tuple[str, str]]: ...
    def _make_transport(
        self,
        fd: int,
        kind: int,
        protocol: asyncio.BaseProtocol,
        waiter: asyncio.Future[None] | None,
        extra: dict[str, Any] | None,
        server: object | None,
        buffered: bool,
    ) -> Transport: ...
